name: Checks
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up the environment
        uses: mskelton/setup-yarn@v1
        with:
          node-version: 14.15.0

      - name: Lint code
        run: yarn run lint
